### ISSUE TITLE
How to manage when cast is deleted 

### ISSUE THREAD

**Issue by manpreetchahal03** [pugson/react-farcaster-embed#10]
this is url [https://warpcast.com/dwr.eth/0x78e746aa](url) and this cast is deleted So I am getting a error on frontend side. So how to manage this
<img width="1440" alt="Screenshot 2024-07-23 at 12 29 11 PM" src="https://github.com/user-attachments/assets/f7133086-3a54-4b9f-8ba3-8ede6a4bf605">

**Comment by pugson** [comment]
You can either pass in your custom cast data JSON to render a deleted cast or use the `silentError` option.

Fixed with 1.8.2.

**Comment by manpreetchahal03** [comment]
and Reply casts are not showing
