### ISSUE TITLE
Corrupt logic in `getCast`

### ISSUE THREAD

**Issue by dalechyn** [pugson/react-farcaster-embed#12]
https://github.com/pugson/react-farcaster-embed/blob/709afbee8b4f37d4da3a2e20e43dc529c65b2277/src/api.ts#L4-L48

Hi.

Using this cast hash `0x3a19c97e69f8d1d25057a6a6811f8d11e1d5a095` renders an incorrect cast.
I don't think that manually picking over casts here is a right solution as currently it only handles 5 levels deep replies.

I get that using farcaster.tv is a good choice for those who don't want to pay for API providers but it really is blocking using this library from using in a production app.

I'd suggest either adding overrideable `getCast` function in options, or adding neynar for retrieving casts.

**Comment by pugson** [comment]
is this fixed with your PR #13 or do you need some more options?
