### ISSUE TITLE
"unable to fetch cast" error

### ISSUE THREAD

**Issue by deeksharungta** [pugson/react-farcaster-embed#3]
I'm getting an "unable to fetch cast" error when navigating between pages. It starts working again when i reload the page. Both pages include embedded casts using the farcaster embed client-side library within a Next.js pages router application.

Attaching a screen recording of the error

https://github.com/pugson/react-farcaster-embed/assets/79518532/ac607be3-7457-468c-9b5e-9b6e1a09e15f

Here's how I'm rendering the component

```
 <div>
        {!!casts?.length &&
          casts?.map((cast) => (
            <div
              key={cast.hash}
            >
              <FarcasterEmbed hash={cast.hash} username={username} />
            </div>
          ))}
  </div>

```

**Comment by pugson** [comment]
I guess you might be getting rate limited by the API proxy. Can you upgrade to 1.4.8 and check the console for errors to see what might be going on? I added more logging.

**Comment by deeksharungta** [comment]
This is what I'm getting after the upgrade, attaching a screenshot of console and network tab

![Screenshot 2024-05-07 at 12 59 00 PM](https://github.com/pugson/react-farcaster-embed/assets/79518532/66a9e2b4-4118-4dfb-8eab-e8755b2cf44d)
![Screenshot 2024-05-07 at 1 03 15 PM](https://github.com/pugson/react-farcaster-embed/assets/79518532/54413219-a942-442a-8a8a-9e37968d1f3f)

**Comment by pugson** [comment]
Looks like that cast does not exist, and I assume the others do not as well.
- https://warpcast.com/dwr.eth/0x47369f9c
- https://warpcast.com/dwr.eth/0x47369f9ccbaf7f7d85ccld20583ef968e94d79cb

**Comment by deeksharungta** [comment]
You're right, some of the casts are not available, but there are still some which are available but still show unable to fetch cast. See this one, for instance.

![Screenshot 2024-05-07 at 8 30 09 PM](https://github.com/pugson/react-farcaster-embed/assets/79518532/74858ad1-0d07-4848-b142-48dea2409621)

https://warpcast.com/dwr.eth/0x81a2dd19b28e513101749b7f5002436073c6bcbc

It seems like I'm getting rate limited. Can I host the API from my end to avoid this, since I have a very large use case where I need to fetch and display a lot of casts at once?

**Comment by pugson** [comment]
Sure. I'll make a new release for setting a custom API URL and open source the proxy in the next couple of days.
