### ISSUE TITLE
Weird behaviour with reply cast url

### ISSUE THREAD

**Issue by dalechyn** [pugson/react-farcaster-embed#7]
https://warpcast.com/proxystudio.eth/0xcdc2d580

Check out this cast. When this URL is used, for some reasons no this reply cast is shown but instead the initial cast.

**Comment by pugson** [comment]
good catch, thanks! fixed in `1.7.1`

**Comment by thebitparticle** [comment]
Why not allow to show a reply in the embed if the reply link is passed despite being made by another author and not the initial cast's author?
