### ISSUE TITLE
XHR request spam to video stream

### ISSUE THREAD

**Issue by dalechyn** [pugson/react-farcaster-embed#8]
When trying to render a cast embed that has a video in it, some kind of XHR spam is started and it throttles the whole website that renders the embed.

https://warpcast.com/artivilla.eth/0x532d9e20

you can test it on this cast.

![Screenshot 2024-07-01 at 17 57 20](https://github.com/pugson/react-farcaster-embed/assets/35642018/97f47d4b-f334-44f4-84e6-e424a16847e9)
![Screenshot 2024-07-01 at 17 57 33](https://github.com/pugson/react-farcaster-embed/assets/35642018/ecabc308-8c1f-418e-9e03-4a3be78925ad)

**Comment by pugson** [comment]
is this when using the app router in next.js?

**Comment by dalechyn** [comment]
> is this when using the app router in next.js?

yes, I'm using this library with Next.js with App Router.
