### ISSUE TITLE
Replies to Replies do not Render properly 

### ISSUE THREAD

**Issue by thebitparticle** [pugson/react-farcaster-embed#9]
The below code checks only for reply of the cast and it works fine but when you pass cast url of a reply of a reply, it breaks and shows the OG cast only because the code below checks only for 3rd item in the list and not the 4th item

```
if (
      cast.result.casts[2] &&
      cast.result.casts[2].author.username === username &&
      cast.result.casts[2].hash.includes(hash)
    ) {
      return cast.result.casts[2];
    }
```

Sample reply of an reply does not render properly - https://www.warpcast.com/saxenasaheb.eth/0x18609044"

**Comment by pugson** [comment]
Thanks for flagging the issue. This should be fixed when you update to 1.8.3
